# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About EMMA"
  url = "#Welcome"
  weight = 10

[[main]]
  name = "Blog Posts"
  url = "#posts"
  weight = 20
  
[[main]]
  name = "Publications"
  url = "#materials"
  weight = 25
  
  [[main]]
  name = "IAA"
  url = "https://www.emma-accessibility.org/post/iaa/"
  weight = 30

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 50

[[main]]
  name = "Team"
  url = "#people"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
